language: python
python:
  - 2.7
  - 3.6
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - bash test.sh
after_success:
  coveralls
